---
- name: Deploy Windows10 VM
  vmware_guest:
    hostname: "{{ esxi_host }}"
    username: "{{ user }}"
    password: "{{ password }}"
    datacentoer: Datacenter
    validate_certs: False
    folder: /hogehoge
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ template }}"

    disk:
     - size_gb: "{{ vm_disk }}"
       type: thin
       datastore: datastore3
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpu_cores_per_socket: "{{ vm_cpu }}"
      scsi: paravirtual

    networks:
     - name: VM Network
       ip: "{{ vm_ip }}"
       netmask: 255.255.255.0
       gateway: 192.168.79.254
    wait_for_ip_address: yes

    customization:
      autologon: yes
      password: root
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  delegate_to: localhost
  
